site_name: Stake Dev Kit (Math-Engine)
site_url: https://carrot-engineering.github.io/math-sdk
theme:
  favicon: assets/favicon.png
  logo: assets/stake_logo_white.svg
  name: material
  palette:
    - scheme: slate
      primary: 'custom'
      accent: 'custom'  
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: default
      primary: 'custom'
      accent: 'custom'
      toggle:
        icon: material/weather-night
        name: Dark mode

  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.action.edit

extra_css:
  - styles/stake.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


nav:
  # - 
  # - Carrot SDK: home.md
  # - Stake Dev Kit (Math):
  - Home: index.md

  - Technical Details:
    - SDK Directory: directory.md
    - Engine Setup: general_overview.md
    - High-Level Structure:
        - State Machine: overview_section/state_overview.md
        - Game Structure: overview_section/game_struct.md
        - Game Format: overview_section/game_format.md

    - Gamestate Structure:
      - Simulation Acceptance: gamestate_section/repeat_info.md
      - Setup: 
        - Configs: gamestate_section/configuration_section/config_overview.md
        - BetMode: gamestate_section/configuration_section/betmode_overview.md
        - Distribution: gamestate_section/configuration_section/betmode_dist.md
      - Symbols and Board:
        - Symbols: gamestate_section/syms_board_section/symbol_info.md
        - Board: gamestate_section/syms_board_section/board_info.md
      - Wins: gamestate_section/win_info.md
      - Events: gamestate_section/events_info.md
      - Force Files: gamestate_section/force_info.md

    - Source Files:
      - Calculations: 
        - Board: source_section/board_info.md
        - Tumble: source_section/tumble_info.md
        - Lines: source_section/lines_info.md
        - Ways: source_section/ways_info.md
        - Scatter: source_section/scatter_info.md
        - Cluster: source_section/cluster_info.md
      - Config: source_section/config_info.md
      - Events: source_section/event_info.md
      - Executables: source_section/executables_info.md
      - State: source_section/state_info.md
      - Win Manager: source_section/win_manager.md
      - Outputs: source_section/file_info.md

    - Utilities: utils_section/utilities.md
    - Example Games: sample_section/sample_games.md
    - Uploads: uploads_section/upload_info.md
    
    - Optimization Algorithm: optimization_section/optimization_algorithm.md

    - Tests: tests_section/test_info.md
    