site_name: Carrot MathEngine
site_url: https://github.com/twist-gaming/zuck-engine
theme:
  favicon: assets/favicon.ico
  logo: assets/carrot.png
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  font:
    text: Merriweather Sans
    code: Red Hat Mono


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Home: index.md
  - Engine Setup: general_overview.md
  - High-Level Structure:
      - State Machine: overview_section/state_overview.md
      - Game Structure: overview_section/game_struct.md
      - Game Format: overview_section/game_format.md

  - Gamestate Structure:
    - Simulation Acceptance: gamestate_section/repeat_info.md
    - Setup: 
      - Configs: gamestate_section/configuration_section/config_overview.md
      - BetMode: gamestate_section/configuration_section/betmode_overview.md
      - Distribution: gamestate_section/configuration_section/betmode_dist.md
    - Gamestate: 
      - gamestate: gamestate_section/gamestate_overview.md
      - executables: gamestate_section/gamestate_executables.md
      - calculations: gamestate_section/gamestate_calculations.md
      - override: gamestate_section/gamestate_override.md
    - Symbols and Board:
      - symbols: gamestate_section/syms_board_section/symbol_info.md
      - board: gamestate_section/syms_board_section/board_info.md
    - Wins: gamestate_section/win_info.md
    - Events: gamestate_section/events_info.md
    - Force Files: gamestate_section/force_info.md

  - Source Files:
    - Calculations: 
      - Board: source_section/board_info.md
      - Tumble: source_section/tumble_info.md
      - Lines: source_section/lines_info.md
      - Ways: source_section/ways_info.md
      - Scatter: source_section/scatter_info.md
      - Cluster: source_section/cluster_info.md
    - Config: source_section/config_info.md
    - Events: source_section/event_info.md
    - Executables: source_section/executables_info.md
    - State: source_section/state_info.md
    - Win Manager: source_section/win_manager.md
    - Outputs: source_section/file_info.md

  - Utilities[NA]: utils_section/utilities.md
  - Example Games: sample_section/sample_games.md
  - Uploads [NA]: uploads_section/upload_info.md

  - Tests [NA]: tests_section/test_info.md
  
  - Optimization Algorithm [NA]: optimization_section/optimization_algorithm.md
